version: 2
updates:
  - commit-message:
      prefix: chore
    directory: /
    package-ecosystem: npm
    schedule:
      interval: monthly
      day: saturday
    reviewers:
      - "mendersoftware/qa-dependabot-reviewers"
